// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVuc10cc7AO7c5GY6ErfcKiO5xfap933I',
    appId: '1:879645158962:web:d36e4736d5b10bb7cc162b',
    messagingSenderId: '879645158962',
    projectId: 'academiaproducts',
    authDomain: 'academiaproducts.firebaseapp.com',
    storageBucket: 'academiaproducts.appspot.com',
    measurementId: 'G-JJXFYN7SMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZSbq9M1f74P5VddY_uYWsXehs_hD5K6Q',
    appId: '1:879645158962:android:0d7957b683abbfb2cc162b',
    messagingSenderId: '879645158962',
    projectId: 'academiaproducts',
    storageBucket: 'academiaproducts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxj4nGacVBu_6IFbUdQ_hvERStBQXzmho',
    appId: '1:879645158962:ios:492068b1d88cedb2cc162b',
    messagingSenderId: '879645158962',
    projectId: 'academiaproducts',
    storageBucket: 'academiaproducts.appspot.com',
    iosClientId: '879645158962-1nnjr85p9b4tr2b6pkp4ken9cm4dvjah.apps.googleusercontent.com',
    iosBundleId: 'com.example.academiaProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxj4nGacVBu_6IFbUdQ_hvERStBQXzmho',
    appId: '1:879645158962:ios:2ebe5238a6a9123ecc162b',
    messagingSenderId: '879645158962',
    projectId: 'academiaproducts',
    storageBucket: 'academiaproducts.appspot.com',
    iosClientId: '879645158962-nvtn72j4ok0ngv4hmdee7hkmr80qjfa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.academiaProducts.RunnerTests',
  );
}
